### ISSUE TITLE
Invalid file access ownership for generated certificates and keys on some systems.

### ISSUE THREAD

**Issue by tomcz7** [bob-california/opensearch-keycloak#2]
On a linux system when current user have different UID/GID than 1000 containers can't access both certificates and keys.

**Comment by cht42** [comment]
I have those two lines at the end of `setup_cert` script and they do the job for me 
```bash
chmod 700 certs/{ca,os-dashboards,os}
chmod 600 certs/{ca/*,os-dashboards/*,os/*}
```

**Comment by tomcz7** [comment]
Hi w needed to change certs/ ownership like that:
`sudo chown -R 1000:1000 certs/`
since inside container the user is UID / GID is same.

In a typical linux installation with a single user current script is working, but my installation has user id and guid from LDAP so it differs from 1000:1000 :)  .
